# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0cd3b516f8baf828d0231ebdeb58c1a5518495d95d928e83e3b90cb2179aee569bca35abd7638cae83a6b4ba0cfa933da12fb813e4d0d9db16e87f06b1bf7374

test:
  secret_key_base: 911488aa8f57ef1a6f25023d9cdca72a67092078504be362fb0b91e468f065b0127fe124952a7a5d742267ddd070730c67eefa2b7a133fc353f74bd587b0cef9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
